### ISSUE TITLE
Unable to write data on real-time database from KMM project

### ISSUE THREAD

**Issue by TufelmalikPQC** [GitLiveApp/firebase-kotlin-sdk#661]
**### I'm working on kmm project and when i'm going to write the data on firebase real-time database then my application will crash and getting this error.**

 **### java.lang.NoClassDefFoundError: Failed resolution of: Ldev/gitlive/firebase/EncodeSettings$BuilderImpl;**

Gradle dependencies:

commonMain.dependencies {

 //Firebase
            implementation(libs.firebase.common)
            implementation(libs.firebase.storage)
            implementation(libs.firebase.database)
            implementation(libs.firebase.crashlytics)
            implementation(libs.firebase.firestore)
            implementation(libs.firebase.messaging)
// other
}

libs.versions.toml:

firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebaseBom" }
firebase-common = { module = "dev.gitlive:firebase-common", version.ref = "firebaseCommon" }
firebase-auth = { module = "dev.gitlive:firebase-auth", version.ref = "firebaseAuth" }
firebase-crashlytics = { module = "dev.gitlive:firebase-crashlytics", version.ref = "firebaseCrashlytics" }
firebase-firestore = { module = "dev.gitlive:firebase-firestore", version.ref = "firebaseFirestore" }
firebase-storage = { module = "dev.gitlive:firebase-storage", version.ref = "firebaseStorage" }
firebase-database = { module = "dev.gitlive:firebase-database", version.ref = "firebaseStorage" }
firebase-messaging = { module = "dev.gitlive:firebase-messaging", version.ref = "firebaseMessaging" }

firebaseAuth = "1.12.0"
firebaseBom = "33.5.1"
firebaseCommon = "2.1.0"
firebaseFirestore = "1.12.0"
firebaseStorage = "1.12.0"
firebaseMessaging = "2.1.0"
firebaseCrashlytics = "1.12.0"

Any one have any idea how to solve then please help me.

**Comment by anggrayudi** [comment]
The cause is in your version catalog: you're mixing 1.x and 2.x of this SDK in the same build.

```toml
firebaseCommon      = "2.1.0"     # 2.x
firebaseMessaging   = "2.1.0"     # 2.x
firebaseAuth        = "1.12.0"    # 1.x
firebaseFirestore   = "1.12.0"    # 1.x
firebaseStorage     = "1.12.0"    # 1.x
firebaseCrashlytics = "1.12.0"    # 1.x
```

`EncodeSettings.BuilderImpl` moved between those majors:

| version | module | package |
|---|---|---|
| 1.12.0 | `firebase-common` | `dev.gitlive.firebase` |
| 2.x | `firebase-common-internal` | `dev.gitlive.firebase.internal` |

Your error is `Ldev/gitlive/firebase/EncodeSettings$BuilderImpl;` — the **1.x** coordinate. Your `firebase-database:1.12.0` was compiled against it, but Gradle resolves `firebase-common` to the highest requested version, which is the 2.1.0 you declared, and in 2.x that class no longer exists at that package. It's present at compile time and missing at runtime, which is exactly what `NoClassDefFoundError` means.

**Fix: put every `dev.gitlive:firebase-*` module on one version.**

```toml
[versions]
gitlive = "2.5.0"

[libraries]
firebase-auth        = { module = "dev.gitlive:firebase-auth",        version.ref = "gitlive" }
firebase-crashlytics = { module = "dev.gitlive:firebase-crashlytics", version.ref = "gitlive" }
firebase-database    = { module = "dev.gitlive:firebase-database",    version.ref = "gitlive" }
firebase-firestore   = { module = "dev.gitlive:firebase-firestore",   version.ref = "gitlive" }
firebase-messaging   = { module = "dev.gitlive:firebase-messaging",   version.ref = "gitlive" }
firebase-storage     = { module = "dev.gitlive:firebase-storage",     version.ref = "gitlive" }
```

Two smaller things worth fixing while you're in there:

- `firebase-database = { ..., version.ref = "firebaseStorage" }` points database at the *storage* version ref. It happens to resolve today because both were `1.12.0`, but it's a trap waiting to fire the next time you bump one and not the other.
- You probably don't need `dev.gitlive:firebase-common` declared at all. The feature modules depend on it with `api`, so it comes in transitively at a consistent version — declaring it separately is how the mismatch got introduced here in the first place.

Be aware that 1.12.0 → 2.x is a major upgrade and there are API changes beyond this one (the `internal` package reorganisation above is part of it), so expect some compile errors to work through. Verify afterwards with:

```
./gradlew :yourAndroidModule:dependencies --configuration debugRuntimeClasspath | grep gitlive
```

Every line should show the same version.
